apiVersion: v1
kind: Service
metadata:
  name: mi-app-service
spec:
  selector:
    app: mi-app-web
  ports:
    - protocol: TCP
      port: 80 # Puerto que expone el servicio
      targetPort: 80 # Puerto de tu contenedor
  type: NodePort # Permite acceder desde tu máquina local